### ISSUE TITLE
Add class configuration section to assemblers

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/website#79]
The assemblers page is missing information about how to configure a default assembler:

```
classes:
  org:
    generated:
      project:
        defaultAssembler: ...
```

Use the same form as in http://seedstack.org/docs/business/repositories/#class-configuration
